import { 
  Sparkles, Scroll, Sword, Zap, Heart, Skull, Anchor, Leaf, 
  Flame, Moon, Hammer, Wind, Drama, Star, Eye, Sun, Music, Crown, Feather,
  Cloud, Ghost,
  // New icons for symbols
  Crop, Castle, Globe, Layers, Mountain, Pickaxe, Wheat, House, EyeOff, 
  Apple, Target, Circle, Wand, Wine, Shirt, AlignJustify, Gavel, 
  Coffee, Egg, Award, Shield, Hourglass, Gem, Trophy,
  // Animal Icons
  Bird, Cat, Dog, Fish, Rabbit, Turtle, Rat, Bug, PawPrint, Activity as Snake
} from 'lucide-react';
import { God } from './types';

// Images are referenced from the public/image directory.
// The UI will currently display the fallback (gradient + icon) if the image file is missing.

export const godsData: God[] = [
  // Titans
  { 
    id: 10, 
    greekName: "Cronus (克洛诺斯)", 
    romanName: "Saturn (萨图恩)", 
    title: "King of the Titans", 
    domain: "Time", 
    symbol: "Sickle", 
    symbolIcon: Moon, 
    animal: "Snake", 
    animalIcon: Snake, 
    icon: Skull, 
    image: "/image/cronus.png", 
    color: "from-stone-600 to-stone-800", 
    desc: "Leader of the Titans. Swallowed his children to prevent prophecy.", 
    quote: "Time devours all.", 
    family: { parents: [], partners: [11], children: [1, 2, 3, 7, 9, 12] },
    plathPoems: ["The Colossus"] 
  },
  { 
    id: 11, 
    greekName: "Rhea (瑞亚)", 
    romanName: "Ops (奥普斯)", 
    title: "Mother of Gods", 
    domain: "Motherhood", 
    symbol: "Turret Crown", 
    symbolIcon: Castle, 
    animal: "Lion", 
    animalIcon: Cat,
    icon: Heart, 
    image: "/image/rhea.png", 
    color: "from-amber-700 to-orange-800", 
    desc: "Titaness who saved Zeus from Cronus.", 
    quote: "Life finds a way.", 
    family: { parents: [], partners: [10], children: [1, 2, 3, 7, 9, 12] } 
  },
  { 
    id: 40, 
    greekName: "Prometheus (普罗米修斯)", 
    romanName: "Prometheus (普罗米修斯)", 
    title: "The Fire Bringer", 
    domain: "Forethought", 
    symbol: "Flame", 
    symbolIcon: Flame,
    animal: "Eagle", 
    animalIcon: Bird,
    icon: Flame, 
    image: "/image/prometheus.png", 
    color: "from-orange-700 to-red-900", 
    desc: "Titan who stole fire from the gods and gave it to humanity.", 
    quote: "I would not change my evil plight for your servitude.", 
    family: { parents: [], partners: [], children: [] },
    plathPoems: [] 
  },
  { 
    id: 41, 
    greekName: "Atlas (阿特拉斯)", 
    romanName: "Atlas (阿特拉斯)", 
    title: "The Titan Bearer", 
    domain: "Endurance", 
    symbol: "Globe", 
    symbolIcon: Globe,
    animal: "Bull", 
    animalIcon: PawPrint,
    icon: Cloud, 
    image: "/image/atlas.png", 
    color: "from-stone-600 to-stone-800", 
    desc: "Condemned to hold up the celestial heavens for eternity.", 
    quote: "The weight of the world is mine.", 
    family: { parents: [], partners: [], children: [18] },
    plathPoems: [] 
  },
  { 
    id: 17, 
    greekName: "Leto (勒托)", 
    romanName: "Latona (拉托娜)", 
    title: "Goddess of Motherhood", 
    domain: "Motherhood", 
    symbol: "Veil", 
    symbolIcon: Cloud, 
    animal: "Rooster", 
    animalIcon: Bird,
    icon: Star, 
    image: "/image/leto.png", 
    color: "from-indigo-300 to-indigo-500", 
    desc: "Titaness mother of the twin archers.", 
    quote: "A mother's love endures.", 
    family: { parents: [], partners: [1], children: [8, 13] } 
  },
  { 
    id: 18, 
    greekName: "Maia (迈亚)", 
    romanName: "Maia (迈亚)", 
    title: "Eldest Pleiad", 
    domain: "Growth", 
    symbol: "Cave", 
    symbolIcon: Mountain,
    animal: "Tortoise", 
    animalIcon: Turtle,
    icon: Sparkles, 
    image: "/image/maia.png", 
    color: "from-emerald-300 to-emerald-500", 
    desc: "Mother of Hermes, lived in a cave.", 
    quote: "Quiet growth leads to greatness.", 
    family: { parents: [41], partners: [1], children: [15] } 
  },
  { 
    id: 19, 
    greekName: "Semele (塞墨勒)", 
    romanName: "Stimula (斯蒂穆拉)", 
    title: "Princess of Thebes", 
    domain: "Mortality", 
    symbol: "Crown", 
    symbolIcon: Crown,
    animal: "Bull", 
    animalIcon: PawPrint,
    icon: Heart, 
    image: "/image/semele.png", 
    color: "from-rose-300 to-rose-500", 
    desc: "Mortal mother of Dionysus.", 
    quote: "Passion burns bright.", 
    family: { parents: [], partners: [1], children: [16] } 
  },
  
  // Olympians (Gen 1)
  { 
    id: 1, 
    greekName: "Zeus (宙斯)", 
    romanName: "Jupiter (朱庇特)", 
    title: "King of the Gods", 
    domain: "Sky, Thunder", 
    symbol: "Thunderbolt", 
    symbolIcon: Zap,
    animal: "Eagle", 
    animalIcon: Bird,
    icon: Zap, 
    image: "/image/zeus.png", 
    color: "from-amber-400 to-yellow-600", 
    desc: "Ruler of Olympus. Wields lightning.", 
    quote: "Even gods bow to fate.", 
    family: { parents: [10, 11], partners: [2, 17, 18, 19, 37], children: [4, 5, 8, 13, 14, 15, 16, 20, 30, 34, 35, 39] } 
  },
  { 
    id: 2, 
    greekName: "Hera (赫拉)", 
    romanName: "Juno (朱诺)", 
    title: "Queen of the Gods", 
    domain: "Marriage", 
    symbol: "Diadem", 
    symbolIcon: Crown, 
    animal: "Peacock", 
    animalIcon: Feather,
    icon: Sparkles, 
    image: "/image/hera.png", 
    color: "from-purple-500 to-indigo-600", 
    desc: "Protector of marriage, known for jealousy.", 
    quote: "Marriage is sacred.", 
    family: { parents: [10, 11], partners: [1], children: [5, 14, 30] } 
  },
  { 
    id: 3, 
    greekName: "Poseidon (波塞冬)", 
    romanName: "Neptune (涅普顿)", 
    title: "God of the Sea", 
    domain: "Sea, Storms", 
    symbol: "Trident", 
    symbolIcon: Anchor, 
    animal: "Horse", 
    animalIcon: PawPrint,
    icon: Anchor, 
    image: "/image/poseidon.png", 
    color: "from-blue-500 to-cyan-600", 
    desc: "Lord of the oceans and earthquakes.", 
    quote: "The sea cannot be restrained.", 
    family: { parents: [10, 11], partners: [21], children: [33] } 
  },
  { 
    id: 9, 
    greekName: "Demeter (德墨忒尔)", 
    romanName: "Ceres (刻瑞斯)", 
    title: "Goddess of Harvest", 
    domain: "Agriculture", 
    symbol: "Cornucopia", 
    symbolIcon: Wheat,
    animal: "Pig", 
    animalIcon: PawPrint,
    icon: Leaf, 
    image: "/image/demeter.png", 
    color: "from-green-500 to-emerald-700", 
    desc: "Controls the seasons and harvest.", 
    quote: "From earth, life springs.", 
    family: { parents: [10, 11], partners: [1], children: [20] } 
  },
  { 
    id: 12, 
    greekName: "Hestia (赫斯提亚)", 
    romanName: "Vesta (维斯塔)", 
    title: "Goddess of Hearth", 
    domain: "Home", 
    symbol: "Hearth Fire", 
    symbolIcon: House,
    animal: "Donkey", 
    animalIcon: PawPrint,
    icon: Flame, 
    image: "/image/hestia.png", 
    color: "from-orange-400 to-red-500", 
    desc: "Virgin goddess of the home.", 
    quote: "The fire of home never dies.", 
    family: { parents: [10, 11], partners: [], children: [] } 
  },
  { 
    id: 7, 
    greekName: "Hades (哈迪斯)", 
    romanName: "Pluto (普鲁托)", 
    title: "King of Underworld", 
    domain: "The Dead", 
    symbol: "Helm", 
    symbolIcon: EyeOff, 
    animal: "Cerberus", 
    animalIcon: Dog,
    icon: Skull, 
    image: "/image/hades.png", 
    color: "from-gray-700 to-gray-900", 
    desc: "Stern ruler of the dead.", 
    quote: "Death comes to all.", 
    family: { parents: [10, 11], partners: [20], children: [] } 
  },
  { 
    id: 43, 
    greekName: "Nyx (倪克斯)", 
    romanName: "Nox (诺克斯)", 
    title: "Goddess of Night", 
    domain: "Night", 
    symbol: "Shadows", 
    symbolIcon: Cloud,
    animal: "Owl", 
    animalIcon: Bird,
    icon: Moon, 
    image: "/image/nyx.png", 
    color: "from-indigo-900 to-black", 
    desc: "Primordial goddess of the night, feared even by Zeus.", 
    quote: "Darkness is the mother of all.", 
    family: { parents: [], partners: [], children: [] },
    plathPoems: [] 
  },
  
  // Olympians (Gen 2)
  { 
    id: 20, 
    greekName: "Persephone (珀耳塞福涅)", 
    romanName: "Proserpina (普洛塞庇娜)", 
    title: "Queen of the Underworld", 
    domain: "Spring, Death", 
    symbol: "Pomegranate", 
    symbolIcon: Apple,
    animal: "Bat", 
    animalIcon: Ghost,
    icon: Leaf, 
    image: "/image/persephone.png", 
    color: "from-fuchsia-800 to-rose-900", 
    desc: "Goddess of spring growth. Queen of the Underworld.", 
    quote: "I am the gate of life and death.", 
    family: { parents: [1, 9], partners: [7], children: [] },
    plathPoems: ["Two Sisters of Persephone"]
  },
  { 
    id: 21, 
    greekName: "Medusa (美杜莎)", 
    romanName: "Medusa (美杜莎)", 
    title: "The Gorgon", 
    domain: "Terror, Stone", 
    symbol: "Snakes", 
    symbolIcon: Snake,
    animal: "Snake", 
    animalIcon: Snake,
    icon: Eye, 
    image: "/image/medusa.png", 
    color: "from-stone-500 to-emerald-900", 
    desc: "Gorgon with snake hair. Former priestess of Athena.", 
    quote: "Look at me and know silence.", 
    family: { parents: [], partners: [3], children: [] },
    plathPoems: ["Medusa"]
  },
  { 
    id: 22, 
    greekName: "Eros (厄洛斯)", 
    romanName: "Cupid (丘比特)", 
    title: "God of Desire", 
    domain: "Love, Passion", 
    symbol: "Bow", 
    symbolIcon: Target,
    animal: "Hare", 
    animalIcon: Rabbit,
    icon: Heart, 
    image: "/image/eros.png", 
    color: "from-pink-300 to-rose-400", 
    desc: "Primal force of desire.", 
    quote: "Love strikes like lightning.", 
    family: { parents: [5, 6], partners: [42], children: [] },
    plathPoems: ["The Great Carbuncle"]
  },
  { 
    id: 42, 
    greekName: "Psyche (普赛克)", 
    romanName: "Psyche (普赛克)", 
    title: "Goddess of the Soul", 
    domain: "Soul", 
    symbol: "Butterfly", 
    symbolIcon: Feather,
    animal: "Butterfly", 
    animalIcon: Bug,
    icon: Ghost, 
    image: "/image/psyche.png", 
    color: "from-sky-100 to-blue-200", 
    desc: "The mortal princess who became the goddess of the soul through love.", 
    quote: "Love cannot live where there is no trust.", 
    family: { parents: [], partners: [22], children: [] },
    plathPoems: [] 
  },
  { 
    id: 23, 
    greekName: "Helios (赫利俄斯)", 
    romanName: "Sol (索尔)", 
    title: "The Colossus", 
    domain: "Sun, Sight", 
    symbol: "Chariot", 
    symbolIcon: Sun,
    animal: "Rooster", 
    animalIcon: Bird,
    icon: Sun, 
    image: "/image/helios.png", 
    color: "from-yellow-500 to-amber-700", 
    desc: "The Sun Titan. Driver of the sun chariot.", 
    quote: "I see all things.", 
    family: { parents: [], partners: [], children: [31] },
    plathPoems: ["The Colossus"]
  },
  { 
    id: 24, 
    greekName: "Pan (潘)", 
    romanName: "Faunus (法乌努斯)", 
    title: "God of the Wild", 
    domain: "Nature, Panic", 
    symbol: "Flute", 
    symbolIcon: Music,
    animal: "Goat", 
    animalIcon: PawPrint,
    icon: Music, 
    image: "/image/pan.png", 
    color: "from-green-600 to-stone-600", 
    desc: "Goat-god of the wild.", 
    quote: "Panic is the sound of nature.", 
    family: { parents: [15], partners: [], children: [] },
    plathPoems: ["Faun", "Virgin in a Tree", "Dialogue Over a Ouija Board"]
  },
  { 
    id: 25, 
    greekName: "Hecate (赫卡忒)", 
    romanName: "Trivia (特里维亚)", 
    title: "Goddess of Magic", 
    domain: "Witchcraft, Ghosts", 
    symbol: "Torches", 
    symbolIcon: Flame,
    animal: "Dog", 
    animalIcon: Dog,
    icon: Moon, 
    image: "/image/hecate.png", 
    color: "from-stone-800 to-purple-900", 
    desc: "Goddess of the dark moon and crossroads.", 
    quote: "I hold the keys to the dark.", 
    family: { parents: [], partners: [], children: [] } 
  },

  { 
    id: 4, 
    greekName: "Athena (雅典娜)", 
    romanName: "Minerva (弥涅尔瓦)", 
    title: "Goddess of Wisdom", 
    domain: "Strategy", 
    symbol: "Aegis", 
    symbolIcon: Shield,
    animal: "Owl", 
    animalIcon: Bird,
    icon: Scroll, 
    image: "/image/athena.png",
    color: "from-slate-400 to-slate-600", 
    desc: "Born from Zeus's head fully armored.", 
    quote: "Wisdom conquers all.", 
    family: { parents: [1], partners: [], children: [] } 
  },
  { 
    id: 5, 
    greekName: "Ares (阿瑞斯)", 
    romanName: "Mars (玛尔斯)", 
    title: "God of War", 
    domain: "War", 
    symbol: "Spear", 
    symbolIcon: Sword,
    animal: "Vulture", 
    animalIcon: Bird,
    icon: Sword, 
    image: "/image/ares.png", 
    color: "from-red-600 to-rose-800", 
    desc: "Untamed aspect of war.", 
    quote: "Conflict creates all.", 
    family: { parents: [1, 2], partners: [6], children: [22] } 
  },
  { 
    id: 6, 
    greekName: "Aphrodite (阿佛洛狄忒)", 
    romanName: "Venus (维纳斯)", 
    title: "Goddess of Love", 
    domain: "Love", 
    symbol: "Mirror", 
    symbolIcon: Circle,
    animal: "Dove", 
    animalIcon: Bird,
    icon: Heart, 
    image: "/image/aphrodite.png", 
    color: "from-pink-400 to-rose-400", 
    desc: "Born from sea foam.", 
    quote: "Love is power.", 
    family: { parents: [], partners: [5, 14], children: [22] } 
  },
  { 
    id: 8, 
    greekName: "Apollo (阿波罗)", 
    romanName: "Apollo (阿波罗)", 
    title: "God of Light", 
    domain: "Prophecy", 
    symbol: "Lyre", 
    symbolIcon: Music, 
    animal: "Raven", 
    animalIcon: Bird,
    icon: Sparkles, 
    image: "/image/apollo.png", 
    color: "from-yellow-300 to-orange-400", 
    desc: "God of music, poetry, art, oracles, archery, plague, medicine, sun, light and knowledge.", 
    quote: "Know thyself.", 
    family: { parents: [1, 17], partners: [], children: [] } 
  },
  { 
    id: 13, 
    greekName: "Artemis (阿尔忒弥斯)", 
    romanName: "Diana (戴安娜)", 
    title: "Goddess of Hunt", 
    domain: "Hunt", 
    symbol: "Bow", 
    symbolIcon: Target,
    animal: "Stag", 
    animalIcon: PawPrint,
    icon: Moon, 
    image: "/image/artemis.png", 
    color: "from-teal-600 to-cyan-800", 
    desc: "Protector of wilderness.", 
    quote: "Wild needs no master.", 
    family: { parents: [1, 17], partners: [], children: [] } 
  },
  { 
    id: 14, 
    greekName: "Hephaestus (赫淮斯托斯)", 
    romanName: "Vulcan (伏尔甘)", 
    title: "God of Forge", 
    domain: "Fire", 
    symbol: "Anvil", 
    symbolIcon: Hammer,
    animal: "Donkey", 
    animalIcon: PawPrint,
    icon: Hammer, 
    image: "/image/hephaestus.png", 
    color: "from-orange-600 to-red-700", 
    desc: "Smith god, cast off Olympus.", 
    quote: "Through fire, create.", 
    family: { parents: [1, 2], partners: [6], children: [] } 
  },
  { 
    id: 15, 
    greekName: "Hermes (赫尔墨斯)", 
    romanName: "Mercury (墨丘利)", 
    title: "Messenger God", 
    domain: "Travel", 
    symbol: "Caduceus", 
    symbolIcon: Wand,
    animal: "Tortoise", 
    animalIcon: Turtle,
    icon: Wind, 
    image: "/image/hermes.png", 
    color: "from-sky-400 to-blue-500", 
    desc: "Swift messenger of the gods.", 
    quote: "Swift as thought.", 
    family: { parents: [1, 18], partners: [], children: [24] } 
  },
  { 
    id: 16, 
    greekName: "Dionysus (狄奥尼索斯)", 
    romanName: "Bacchus (巴克斯)", 
    title: "God of Wine", 
    domain: "Wine", 
    symbol: "Thyrsus", 
    symbolIcon: Wine,
    animal: "Leopard", 
    animalIcon: Cat,
    icon: Drama, 
    image: "/image/dionysus.png", 
    color: "from-fuchsia-700 to-purple-900", 
    desc: "Spreads joy and madness.", 
    quote: "In wine, truth.", 
    family: { parents: [1, 19], partners: [], children: [] } 
  },

  // Plath Additions
  { 
    id: 30, 
    greekName: "Eileithyia (埃勒提亚)", 
    romanName: "Lucina (卢西娜)", 
    title: "Goddess of Childbirth", 
    domain: "Birth, Moon", 
    symbol: "Torch", 
    symbolIcon: Flame,
    animal: "Polecat", 
    animalIcon: Rat,
    icon: Star, 
    image: "/image/eileithyia.png", 
    color: "from-slate-200 to-slate-400", 
    desc: "Bony mother laboring among the socketed white stars.", 
    quote: "Lucina, bony mother, laboring.", 
    family: { parents: [1, 2], partners: [], children: [] },
    plathPoems: ["Moonrise"]
  },
  { 
    id: 31, 
    greekName: "Medea (美狄亚)", 
    romanName: "Medea (美狄亚)", 
    title: "Sorceress of Colchis", 
    domain: "Magic, Tragedy", 
    symbol: "Golden Fleece", 
    symbolIcon: Shirt, 
    animal: "Serpent", 
    animalIcon: Snake,
    icon: Flame, 
    image: "/image/medea.png", 
    color: "from-emerald-700 to-stone-900", 
    desc: "Mother Medea in a green smock, moving humbly as any housewife.", 
    quote: "Cheated of the pyre and the rack.", 
    family: { parents: [23], partners: [], children: [] },
    plathPoems: ["Aftermath"]
  },
  { 
    id: 32, 
    greekName: "Nike (尼凯)", 
    romanName: "Victoria (维多利亚)", 
    title: "Goddess of Victory", 
    domain: "Victory", 
    symbol: "Wings", 
    symbolIcon: Feather,
    animal: "Eagle", 
    animalIcon: Bird,
    icon: Wind, 
    image: "/image/nike.png", 
    color: "from-stone-100 to-stone-300", 
    desc: "Mother of a white Nike. Streaming between my walls.", 
    quote: "The woman is perfected.", 
    family: { parents: [], partners: [], children: [] },
    plathPoems: ["Barren Woman", "The Other"]
  },
  { 
    id: 33, 
    greekName: "Siren (塞壬)", 
    romanName: "Lorelei (罗蕾莱)", 
    title: "River Spirit", 
    domain: "Drowning", 
    symbol: "Song", 
    symbolIcon: Music, 
    animal: "Fish", 
    animalIcon: Fish,
    icon: Music, 
    image: "/image/siren.png", 
    color: "from-cyan-700 to-blue-900", 
    desc: "Sisters, whose song bears a burden too weighty for the whorled ear.", 
    quote: "It is no night to drown in.", 
    family: { parents: [3], partners: [], children: [] },
    plathPoems: ["Lorelei"]
  },
  { 
    id: 34, 
    greekName: "Perseus (珀尔修斯)", 
    romanName: "Perseus (珀尔修斯)", 
    title: "The Hero", 
    domain: "Heroes", 
    symbol: "Severed Head", 
    symbolIcon: Skull, 
    animal: "Pegasus", 
    animalIcon: PawPrint,
    icon: Sword, 
    image: "/image/perseus.png", 
    color: "from-amber-200 to-yellow-500", 
    desc: "The Triumph of Wit Over Suffering. He who borrowed feathers for his feet.", 
    quote: "To you, Perseus, the palm.", 
    family: { parents: [1], partners: [], children: [] },
    plathPoems: ["Perseus"]
  },
  { 
    id: 35, 
    greekName: "Heracles (赫拉克勒斯)", 
    romanName: "Hercules (海格力斯)", 
    title: "God of Strength", 
    domain: "Labors", 
    symbol: "Club", 
    symbolIcon: Gavel,
    animal: "Lion", 
    animalIcon: Cat,
    icon: Hammer, 
    image: "/image/heracles.png", 
    color: "from-red-700 to-orange-800", 
    desc: "Rinsing those stables: a baby's tears would do it.", 
    quote: "By Candlelight, a small brass image.", 
    family: { parents: [1], partners: [], children: [] },
    plathPoems: ["Perseus", "By Candlelight"]
  },
  { 
    id: 36, 
    greekName: "Electra (厄勒克特拉)", 
    romanName: "Electra (厄勒克特拉)", 
    title: "The Grieving Daughter", 
    domain: "Vengeance", 
    symbol: "Urn", 
    symbolIcon: Trophy, 
    animal: "Hound", 
    animalIcon: Dog,
    icon: Skull, 
    image: "/image/electra.png", 
    color: "from-gray-800 to-black", 
    desc: "The day you died I went into the dirt.", 
    quote: "It was my love that did us both to death.", 
    family: { parents: [], partners: [], children: [] },
    plathPoems: ["Electra on Azalea Path", "Daddy"]
  },
  { 
    id: 37, 
    greekName: "Leda (勒达)", 
    romanName: "Leda (勒达)", 
    title: "Queen of Sparta", 
    domain: "Motherhood, Swans", 
    symbol: "Egg", 
    symbolIcon: Egg, 
    animal: "Swan", 
    animalIcon: Bird,
    icon: Leaf, 
    image: "/image/leda.png", 
    color: "from-rose-200 to-stone-300", 
    desc: "Full of wings, otherworldliness. In this, they are Ledas.", 
    quote: "Knowing neither abortions nor bitchery.", 
    family: { parents: [], partners: [1], children: [39] },
    plathPoems: ["Brasilia"]
  },
  { 
    id: 38, 
    greekName: "Daphne (达芙妮)", 
    romanName: "Daphne (达芙妮)", 
    title: "The Laurel Nymph", 
    domain: "Trees, Chastity", 
    symbol: "Laurel Wreath", 
    symbolIcon: Award,
    animal: "Bird", 
    animalIcon: Bird,
    icon: Leaf, 
    image: "/image/daphne.png", 
    color: "from-green-400 to-emerald-600", 
    desc: "Switched her incomparable back for a bay-tree hide.", 
    quote: "Pine-needle armor protects.", 
    family: { parents: [], partners: [], children: [] },
    plathPoems: ["Virgin in a Tree", "On the Difficulty of Conjuring Up a Dryad"]
  },
  { 
    id: 39, 
    greekName: "Helen (海伦)", 
    romanName: "Helena (海伦娜)", 
    title: "Helen of Troy", 
    domain: "Beauty", 
    symbol: "Golden Apple", 
    symbolIcon: Apple, 
    animal: "Swan", 
    animalIcon: Bird,
    icon: Crown, 
    image: "/image/helen.png", 
    color: "from-yellow-200 to-amber-300", 
    desc: "Eclipsing Eva, Cleo and Helen of Troy.", 
    quote: "For which of those would speak?", 
    family: { parents: [1, 37], partners: [], children: [] },
    plathPoems: ["Virgin in a Tree"]
  }
];